REQUIRED_DEVICE_TYPES = [
    # "door_lock",
    # "aggregator",
    "generic_switch",
    # "power_source",
    # "ota_requestor",
    # "bridged_node",
    # "ota_provider",
    "contact_sensor",
    # "root_node",
    # "solar_power",
    # "battery_storage",
    # "secondary_network_interface",
    # "mode_select",
    # "fan",
    "air_quality_sensor",
    # "air_purifier",
    # "water_freeze_detector",
    # "water_valve",
    # "water_leak_detector",
    # "rain_sensor",
    # "soil_sensor",
    # "refrigerator",
    # "temperature_controlled_cabinet",
    # "room_air_conditioner",
    # "laundry_washer",
    # "robotic_vacuum_cleaner",
    # "dishwasher",
    # "smoke_co_alarm",
    # "cook_surface",
    # "cooktop",
    # "microwave_oven",
    # "extractor_hood",
    # "oven",
    # "laundry_dryer",
    # "thread_border_router",
    "on_off_light",
    "dimmable_light",
    "on_off_light_switch",
    "dimmer_switch",
    "color_dimmer_switch",
    "light_sensor",
    "occupancy_sensor",
    # "on_off_plug_in_unit",
    # "dimmable_plug_in_unit",
    "color_temperature_light",
    "extended_color_light",
    # "mounted_on_off_control",
    # "mounted_dimmable_load_control",
    # "audio_doorbell",
    # "camera",
    # "video_doorbell",
    # "chime",
    # "doorbell",
    # "window_covering",
    # "closure",
    # "closure_panel",
    # "closure_controller",
    # "thermostat",
    "temperature_sensor",
    # "pump",
    # "pump_controller",
    "pressure_sensor",
    "flow_sensor",
    "humidity_sensor",
    # "heat_pump",
    # "thermostat_controller",
    # "evse",
    # "device_energy_management",
    # "water_heater",
    # "electrical_sensor",
    # "electrical_utility_meter",
    # "electrical_energy_tariff",
    # "electrical_meter",
    # "control_bridge",
]
